### ISSUE TITLE
Icon SVGs

### ISSUE THREAD

**Issue by rugk** [ENT8R/StreetCompleteQuestCreator#5]
Hmm, did you see my [icon svgs extracted here](https://github.com/rugk/streetcomplete-quest-svgs)? Maybe you can use these as a git submodule or so to not duplicate work here.

Or I just take your files over. Also your filenames are way superior… 😆 (I did not need it for my use case, so… 🤷‍)

**Comment by ENT8R** [comment]
Actually, I used your project for my files. Great work! I decided to not put a StreetComplete prefix into every filename and use the original file names to keep a better overview and better maintainability...

**Comment by rugk** [comment]
So you'd care to rename the files in my "upstream project"? The names are kinda messy: https://github.com/rugk/streetcomplete-quest-svgs/issues/1

**Comment by ENT8R** [comment]
Would be great! Do you want to do that or should I do that, as I know all the file names...

**Comment by rugk** [comment]
Just create a PR.

**Comment by ENT8R** [comment]
I'm done so far but there is one file that I don't know where it comes from... This file: https://github.com/rugk/streetcomplete-quest-svgs/blob/master/optimized/StreetComplete_quest_objectname.svg can't be found in the drawable folder of StreetComplete which means that this is not in use so it does not have a name... I wonder how we should name this file?

**Comment by ENT8R** [comment]
I also added the icon for the vegetarian quest (doesn't seem to be included) but I have no idea how optimization works so it has a size of 19 KB instead of 4 or 5 KB...
This is the file: https://github.com/ENT8R/StreetCompleteQuestCreator/blob/master/assets/icons/ic_quest_restaurant_vegetarian.svg

**Comment by rugk** [comment]
See the Readme, I've just extracted them from the big SVG file. (so maybe just no drawable was created out of it.)

You can send the file as it is, I can still optimize it. (If you want to know or do it, I use [svgo](https://jakearchibald.github.io/svgomg/).)

**Comment by ENT8R** [comment]
OK. Thank you!

**Comment by ENT8R** [comment]
Can this issue be closed now?

**Comment by rugk** [comment]
Yeah, sure.

You could, if you want you could add my repo [as a git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to yours, so you can simply update the SVGs with a `git pull`, but that's your decision.

**Comment by ENT8R** [comment]
I will do it like that! Thank you for the hint!
