### ISSUE TITLE
Commit message?

### ISSUE THREAD

**Issue by rugk** [ENT8R/StreetCompleteQuestCreator#6]
I am also not into StreetComplete's source code, but also this website does not tell me what it is…

So what is the commit message (`getCommitMessage`) used for? I mean, this is in the source, the one you use for git could theoretically vary (it probably should not, but who knows).

**Comment by ENT8R** [comment]
I created a small help page at https://ent8r.github.io/StreetCompleteQuestCreator/help.html
The commit message is not used for Git... It is used to describe the changes which were made in an OSM changeset. I don't know another word for that. Do you think that this needs some adjustment? Do other OSM editors have a word for it?

**Comment by rugk** [comment]
Ah the OSM changeset. I think that's the word they use. ("message for OMS changeset" or so)

**Comment by ENT8R** [comment]
OK. I will change this.
