### ISSUE TITLE
Button quest type

### ISSUE THREAD

**Issue by rugk** [ENT8R/StreetCompleteQuestCreator#7]
I'd would be nice to also have the Yes/No variant quest type in the generation, but with additional buttons.

One button then just generates some template code, (with some `//TODO` comments, and maybe some examples on how to add/modify tags) and the coder then just has to add the code for adding/modifying the tags of the element.

**Comment by ENT8R** [comment]
> I'd would be nice to also have the Yes/No variant quest type in the generation, but with additional buttons.

It is possibly to create a Yes-No quest since the first version...

> One button then just generates some template code, (with some //TODO comments, and maybe some examples on how to add/modify tags) and the coder then just has to add the code for adding/modifying the tags of the element.

But this is what this website/tool should do...
Isn't it easier to have a GUI than to add it yourself? I don't see a big reason why one shouldn't use the GUI...

**Comment by rugk** [comment]
Not only yes/no, but as I said:
>  with additional buttons.

So e.g. three or four buttons…

**Comment by ENT8R** [comment]
I will discontinue to develop this project and archive it now so this feature request will probably never be solved.

**Comment by rugk** [comment]
Don't forget to add a note to the Readme first. Otherwise anyone will wonde3r why this has been archived. :smiley: :+1:

**Comment by ENT8R** [comment]
I'm doing this right now!
